ror/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'sign-in', as: 'sign_in', to: 'auth#sign_in'
  post 'sign-in', as: 'login', to: 'auth#login'
  get 'logout', as: 'logout', to: 'auth#logout'

  get 'create-test-user', as: 'test-sign-in', to: 'auth#test_create_user'
  get 'users', as: 'users', to: 'auth#users'

  scope '/users/:id' do
    get 'posts', as: 'user_posts', to: 'posts#user_posts'
  end

  root 'application#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ror/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ror/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user


  validates :slug, presence: true, uniqueness: true
  validates :title, presence: true, length: { minimum: 4 }
  validates :user_id, presence: true

end

ror/app/models/product.rb
class Product < ApplicationRecord
end

ror/app/models/user.rb
class User < ApplicationRecord

  before_save :lowercase_email

  has_many :post

  def lowercase_email
    self.email = email.downcase
  end

  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/, message: 'Invalid email' }
  validates :password_digest, presence: true, length: { minimum: 4 }
  validates :first_name, presence: true, length: { maximum: 35, minimum: 1}
  validates :last_name, presence: true, length: { maximum: 35, minimum: 1}

  has_secure_password

end

ror/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :auth_check

  helper_method :is_logged?, :current_user

  def is_logged?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def auth_check (redirect_url = nil)
    unless is_logged?
      redirect_url = redirect_url ? redirect_url : login_path
      redirect_to redirect_url
    end
  end

  def index
    
  end

end

ror/app/controllers/auth_controller.rb
class AuthController < ApplicationController

  before_action :auth_check, only: [:logout]

  def sign_in

  end

  def login
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Your have successfully logged in."
      redirect_to root_path
    else
      flash[:warning] = "Either your email or password is incorrect."
      render 'sign_in'
    end
  end

  def logout
    session[:user_id] = nil
    flash[:success] = "Your have successfully logged out."
    redirect_to sign_in_path
  end

  def users
    abort User.all.inspect
  end

  def test_create_user

    res = User.new(
      first_name: 'Test',
      last_name: 'User 1',
      display_name: 'Test User 1',
      email: 'alisajjad11111@gmail.com',
      password: 'test',
      password_confirmation: 'test',
    )

    abort res.save.inspect

  end
end

ror/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  before_action :auth_check, except: [ :index ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def user_posts
    @posts = Post.where(user_id: params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :slug, :body)
    end
end

ror/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @product, status: :created, location: @product }
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    if params[:id]
      respond_to do |format|
        format.html { redirect_to edit_product_path(params[:id]) }
        format.json { render :show, status: :created, location: @product }
      end
    end

    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update

    unless params[:id]
      respond_to do |format|
        format.html { redirect_to new_product_path }
        format.json { render :show, status: :created, location: @product }
      end
    end

    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  def test_create
    Product.create(
      name: "Test Product 1",
      description: "Test description 1"
    )

    redirect_to products_path
  end

  def test_delete_all
    Product.delete_all

    redirect_to products_path
  end

  protected
  def product_params
    params.require(:product).permit(:name, :description)
  end
end

ror/app/helpers/application_helper.rb
module ApplicationHelper
end

ror/app/helpers/auth_helper.rb
module AuthHelper
end

ror/app/helpers/posts_helper.rb
module PostsHelper
end

ror/app/views/application/index.html.erb
<h1>Logged In as <%= current_user.email %>, <%= link_to "Log Out", logout_path %></h1>

ror/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Untitled</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag  "https://use.fontawesome.com/releases/v5.10.2/css/all.css" %>
  <%= stylesheet_link_tag  "https://use.fontawesome.com/releases/v5.10.2/css/v4-shims.css" %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container-fluid">
  
  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <%= yield %>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

ror/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ror/app/views/posts/_posts.html.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Slug</th>
    <th>Body</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.user.display_name %></td>
      <td><%= post.slug %></td>
      <td><%= post.body %></td>
      <td><%= link_to 'Show', post %></td>
      <% if post.user.id == current_user.id %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Remove', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% else %>
        <td>Edit</td>
        <td>Destroy</td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

ror/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

ror/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<%= render 'posts', posts: @posts %>

<br>

<%= link_to 'New Post', new_post_path %>

ror/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

ror/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @post.user.display_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<% if @post.user.id == current_user.id %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>

<%= link_to 'Back', posts_path %>

ror/app/views/posts/user_posts.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Posts</h1>

<%= render 'posts', posts: @posts %>

<br>

<%= link_to 'New Post', new_post_path %>

ror/app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |form| %>
  <% if @product && @product.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h6>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h6>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Product Name" %><br>
    <%= form.text_field :name, :class => 'form-control', placeholder: "Product Name", required: "true" %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Description" %><br>
    <%= form.text_area :description, :class => 'form-control', :rows => 3, required: "true" %>
  </div>

  <% if @product && @product.id.present? %>
    <%= form.submit "Update" %>
  <% else %>
    <%= form.submit "Submit" %>
  <% end %>

<% end %>

ror/app/views/products/edit.html.erb
<h1>Edit a Product</h1>
<%= render 'form' %>

ror/app/views/products/index.html.erb
<h1>Products</h1>

<p> <%= link_to "Add new Product", new_product_path %></p>

<table border="1" cellspacing="1">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Description</th>
    <th colspan="2">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= link_to "Edit", edit_product_path(product) %></td>
      <td><%= link_to 'Delete', product_path(product), method: :delete, data: { confirm: 'Are You sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

ror/app/views/products/new.erb
<h1>Add a Product</h1>
<%= render 'form' %>

ror/app/views/products/show.erb
<h1>Product Information</h1>
<table border="1">
  <tr>
    <th>ID</th>
    <td><%= @product.id %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= @product.name %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @product.description %></td>
  </tr>
  <tr>
    <th>Created At</th>
    <td><%= localize @product.created_at, :format => '%d.%m.%Y' %></td>
  </tr>
  <tr>
    <th>Updated At</th>
    <td><%= localize @product.updated_at,  :format => '%d.%m.%Y' %></td>
  </tr>
</table>